version: 2.1

orbs:
  welcome: circleci/welcome-orb@0.4.1

commands:
  install_dependencies:
    description: Installs all app dependencies
    steps:
      - run: npm i
      - run:
          name: on error
          command: echo "[X] Error!! Could not install dependencies"
          when: on_fail


  lint_code_files:
    description: Makes sure code file is properly formatted
    steps:
      - run: npm run lint
      - run:
          name: on error
          command: echo "[X] Code linting failed!!"
          when: on_fail

  test_code_files:
    description: Makes sure code file work properly
    steps:
      - run: npm run test
      - run:
          name: on error
          command: echo "[X] Some tests were not passed!!"
          when: on_fail

  audit_code_files:
    description: Makes sure code file is properly secured
    steps:
      - run: npm audit
      - run:
          name: on error
          command: echo "[X] Code audit failed!!"
          when: on_fail

jobs: 
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - install_dependencies
      - lint_code_files

  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - install_dependencies
      - test_code_files

  analyze:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - install_dependencies
      - audit_code_files


# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build_test_analyze_code:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test

